version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: vendorpulse-postgres
    environment:
      POSTGRES_DB: vendorpulse
      POSTGRES_USER: vendorpulse
      POSTGRES_PASSWORD: vendorpulse
    ports:
      - "5433:5433"
    volumes:
      - vendorpulse-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vendorpulse"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: vendorpulse-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: vendorpulse-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: vendorpulse-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  vendorpulse-pg-data:
